version: "3.7"

services: 
  backend:
    build: backend/
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: admin


  frontend:
    build: frontend/
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 3000:3000
    
  #database
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin