version: "3.7"

services:
  backend:
    build: backend/
    volumes: 
    - ./backend:/app
    ports:
    - 5000:5000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin

  frontend:
    build: frontend/
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/public:/app/public

    ports:
    - 3000:3000

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin


